SELECT * FROM ACCOUNT
INSERT INTO account(username, PASSWORD, EMAIL, created_on)
VALUES('JOSE', 'PASSWD','JOSE@GMAIL.COM', CURRENT_TIMESTAMP)

INSERT INTO JOB(JOB_NAME)
VALUES('MATHEMATICIAN')

INSERT INTO JOB(JOB_NAME)
VALUES('ASTRONAUT')

SELECT * FROM JOB

INSERT INTO ACCOUNT_JOB(USER_ID, JOB_ID, HIRE_DATE)
VALUES(1, 1, CURRENT_TIMESTAMP)


INSERT INTO ACCOUNT_JOB(USER_ID, JOB_ID, HIRE_DATE)
VALUES(1, 1, CURRENT_TIMESTAMP)

SELECT * FROM account_job
-- THE FOLLOWING WILL NOT WORK COZ 2 IS NOT IN ACCOUNT.USER_ID (WHICH WAS A REFERENCE)
INSERT INTO ACCOUNT_JOB(USER_ID, JOB_ID, HIRE_DATE)
VALUES(2, 1, CURRENT_TIMESTAMP)

SELECT * FROM account_job

UPDATE account_job
SET hire_date = CURRENT_TIMESTAMP

UPDATE account
SET last_login = created_on

SELECT * FROM ACCOUNT_JOB

UPDATE ACCOUNT_JOB
SET hire_date = ACCOUNT.created_on
FROM account
WHERE ACCOUNT.user_id = ACCOUNT_JOB.USER_ID

UPDATE ACCOUNT
SET last_login = CURRENT_TIMESTAMP
RETURNING last_login, EMAIL, created_on

DELETE FROM account_job
WHERE USER_ID = 2

INSERT INTO  account_job(user_id, JOB_ID, HIRE_DATE)
VALUES(1,1, CURRENT_TIMESTAMP)


SELECT * FROM account_job

INSERT INTO JOB(JOB_NAME)
VALUES('COWBOY')

SELECT * FROM JOB
DELETE FROM JOB
WHERE JOB_NAME = 'COWBOY'
RETURNING JOB_ID, JOB_NAME

CREATE TABLE INFORMATION(
	INFO_ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(500) NOT NULL,
	PERSON VARCHAR(50) UNIQUE NOT NULL
)

ALTER TABLE INFORMATION
RENAME TO NEW_INFO

SELECT * FROM NEW_INFO

ALTER TABLE new_info
RENAME COLUMN person TO PEOPLE

INSERT INTO new_info(TITLE)
VALUES('SOME TITLE')

ALTER TABLE new_info
ALTER COLUMN PEOPLE DROP NOT NULL


ALTER TABLE new_info
DROP COLUMN people

SELECT * FROM new_info

ALTER TABLE new_info
DROP COLUMN IF EXISTS people

SELECT * FROM new_info

CREATE TABLE EMPLOYEE(
	EM_ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	BIRTHDATE DATE CHECK (BIRTHDATE > '1900-01-01'),
	HIREDATE DATE CHECK (HIREDATE > BIRTHDATE),
	SALARY INTEGER CHECK (SALARY > 0)
)

INSERT INTO employee(FIRST_NAME, LAST_NAME, BIRTHDATE, HIREDATE, SALARY)
VALUES(
	'JOSE',
	'PORTILLA',
	'2001-02-03',
	'2010-01-01',
	100
	)
	
SELECT * FROM employee



