SELECT customer_id,
CASE
	WHEN (CUSTOMER_ID BETWEEN 1 AND 10) THEN 'PREMIUM'
	WHEN (CUSTOMER_ID BETWEEN 100 AND 150) THEN 'PLUS'
	ELSE 'NORMAL'
END as customer_class
FROM customer

SELECT customer_id,
CASE customer_id
	WHEN 1 THEN 'winner'
	WHEN 2 THEN 'second place'
	ELSE 'NORMAL'
END as raffle_results
FROM customer

SELECT COUNT(*) FROM FILM
WHERE RATING = 'PG-13'

SELECT 
SUM(CASE RATING
	WHEN 'R' THEN 1
	ELSE 0
	END) AS R,
SUM(CASE RATING
	WHEN 'PG-13' THEN 1
	ELSE 0
	END) AS PG13,
SUM(CASE RATING
	WHEN 'PG' THEN 1
	ELSE 0
	END) AS PG
FROM FILM

SELECT 
SUM(CASE RATING
	WHEN 'PG-13' THEN 1
	ELSE 0
	END) AS PG13
FROM FILM

SELECT 
SUM(CASE RATING
	WHEN 'PG' THEN 1
	ELSE 0
	END) AS PG
FROM FILM

SELECT '5'::INTEGER

SELECT CHAR_LENGTH(CAST(INVENTORY_ID AS VARCHAR)) FROM RENTAL
WHERE CHAR_LENGTH(CAST(INVENTORY_ID AS VARCHAR)) = 2

CREATE TABLE DEPTS(
FIRSTNAME VARCHAR(50),
DEPS VARCHAR(50))

INSERT INTO DEPTS(FIRSTNAME,
DEPS)
VALUES(
'RAM','A'
),
('SITA','B'),
('HANUMAN','C')


SELECT * FROM DEPTS

SELECT SUM(
CASE WHEN DEPS = 'A' THEN 1 ELSE 0 END)/NULLIF(SUM(
CASE WHEN DEPS = 'B' THEN 1 ELSE 0 END),0) AS RATIO
FROM DEPTS


