CREATE TABLE ACCOUNT(
	USER_ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(50) UNIQUE NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(250) UNIQUE NOT NULL,
	CREATED_ON TIMESTAMP NOT NULL,
	LAST_LOGIN TIMESTAMP
)


CREATE TABLE JOB(
	JOB_ID SERIAL PRIMARY KEY,
	JOB_NAME VARCHAR(200) UNIQUE NOT NULL
)

CREATE TABLE ACCOUNT_JOB(
	USER_ID INTEGER REFERENCES ACCOUNT(USER_ID),
	JOB_ID INTEGER REFERENCES JOB(JOB_ID),
	HIRE_DATE TIMESTAMP
)